name: Deploy
on:
  release:
    types: [published]

jobs:
  deploy-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            8.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal -p:ParallelizeTestCollections=false

      - name: Build solution and generate NuGet package
        run: dotnet pack src/Fenrir.Api -c Release

      - name: Push generated package to NuGet
        run: dotnet nuget push ./src/Fenrir.Api/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
